GlobalManagment/Controllers/ChanellController.cs
using Jandag.BLL.Interface;
using Jandag.BLL.Models;
using Microsoft.AspNetCore.Mvc;

namespace GlobalManagment.Controllers
{
    public class ChanellController : Controller
    {
        private readonly IChanellServices ser;
        public ChanellController(IChanellServices se)
        {
            this.ser = se;
                
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var res = await ser.GetAllAsync();
                return View(res);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string Name)
        {
            if(Name  is not null)
            {
               var res= await ser.DeleteByName(Name);
                if(res)
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            throw new ArgumentException("shecoma");
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Insert(string Name)
        {
            try
            {

                var res = await ser.AddAsync(new ChanellModel()
                {
                    Name = Name,
                });
                if (res)
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Add");
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

GlobalManagment/Controllers/SourceController.cs
using Jandag.BLL.Interface;
using Jandag.BLL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace GlobalManagment.Controllers
{
    public class SourceController : Controller
    {
        private readonly IsourceServices ser;
        public SourceController(IsourceServices ser)
        {
            this.ser = ser;
        }
        public async Task<IActionResult> Index()
        {
            var res = await ser.GetAllAsync();
            return View(res);
        }

        public async Task<IActionResult> Add()
        {
            var re = await ser.GetDropDOwnListData();
            return View(re);
        }

        [HttpPost]
        public async Task<IActionResult> Insert(SourceModel mod)
        {
            mod.port = "Undefined";
            mod.card = "Undefined";
            mod.sourceName = "Undefined";
            mod.EMR = "200";
            mod.Status = false;
            var res = await ser.AddAsync(mod);
            if (res)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var res = await ser.Delete(id);
            if (res)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Add");
        }
    }
}

GlobalManagment/Views/Chanell/Add.cshtml
@using Jandag.BLL.Models
@model ChanellModel
<!DOCTYPE html>
<html>
<head>

    <title>თანამგზავრი</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #B2B377;
            font-family: Arial, sans-serif;
        }

        .container {
            margin-top: 5px;
            border-radius: 30px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 30px;
            background-color: #FFF8DC;
        }

        h2 {
            color: black;
            margin-bottom: 20px;
            margin-left: 210px;
            font-weight: 600;
        }

        .form-group {
            margin-bottom: 30px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        input[type="number"] {
            border: 1px solid #ced4da;
            border-radius: 20px;
            padding: 10px;
            width: 100%;
            font-size: 20px;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif,'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            background-color: #FFF8DC;
            font-weight: 400;
        }

            input[type="text"]:focus,
            input[type="number"]:focus {
                border-color: #007bff;
                outline: none;
            }

        .btn-primary {
            background-color: #007bff;
            border: none;
            border-radius: 120px;
            padding: 10px 20px;
            margin-left: 450px;
        }

            .btn-primary:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <div class="message-box">
        @if (TempData["Error"] != null)
        {
            <div class="error-message">
                <script>
                    alert('@TempData["Error"]');
                </script>
            </div>
        }
        @if (TempData["success"] != null)
        {
            <div class="success-message">
                <script>
                    alert('@TempData["success"]');
                </script>
            </div>
        }
    </div>
    <div class="container">
        <h2>არხის დამატება</h2>
        <form asp-action="Insert" asp-controller="Chanell" method="get">
            <div class="form-group">
                <label for="Port">არხის სახელი</label>
                <input required type="text" class="form-control" name="Name" id="Port" placeholder="მაგ: Imedi" />
            </div>
            <button type="submit" class="btn btn-primary">დამატება</button>
        </form>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

GlobalManagment/Views/Chanell/Index.cshtml
@using Jandag.BLL.Models
@model IEnumerable<ChanellModel>
@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html lang="ka">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Channels Information</title>
    <style>
        body {
            background-color: #B2B377;
            color: #8B4513;
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }

        h1, h2, h3 {
            color: #8B4513;
        }

        a {
            color: #FF4500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        .container {
            max-width: 80%;
            margin: 0 auto;
            background-color: #FFF8DC;
            padding: 20px;
            border-radius: 50px;
        }

        h1, h2 {
            text-align: center;
            color: #333;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        tr{
            background-color: #f9f9f9;
        }
        tr:hover
        {
            background-color:antiquewhite
        }
          

        .error-message, .success-message {
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
        }

        .error-message {
            background-color: #ffcccc;
            color: #cc0000;
        }

        .success-message {
            background-color: #d4edda;
            color: #155724;
        }

        .channel-info {
            background-color: #f7f7f7;
            padding: 10px;
            border-radius: 5px;
        }

        .delete-btn {
            background-color: #dc3545;
        }
        button{
            min-width:20px;
        }

            .delete-btn:hover {
                background-color: #c82333;
            }

        .container {
            text-align: center;
            margin-top: 20px;
        }

        .btn-primary {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin: 5px;
            transition: background-color 0.3s;
        }

            .btn-primary:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <div class="container">
        @if (TempData["Error"] != null)
        {
            <div class="error-message">
                <script>alert('@TempData["Error"]');</script>
            </div>
        }
        @if (TempData["success"] != null)
        {
            <div class="success-message">
                <script>alert('@TempData["success"]');</script>
            </div>
        }
        
        <h2>არხების ინფორმაცია</h2>
        <div class="container">
            <form asp-action="Add" asp-controller="Chanell" method="get">
                <button type="submit" class="btn btn-primary">არხის დამატება</button>
            </form>
            <form asp-action="Index" asp-controller="Source" method="get">
                <button type="submit" class="btn btn-primary">წყაროს დამატება</button>
            </form>
        </div>
        <table>
            <thead>
                <tr>
                    <th>არხის სახელი</th>
                    <th>ინფორმაცია</th>
                    <th>მოქმედება</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var frequency in Model)
                {
                    <tr>
                        <td>@frequency.Name</td>
                        <td>
                    
                            <table>
                                <thead>
                                    <tr>
                                        <th>ფორმატი</th>
                                        <th>სტატუსი</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in frequency.Sources)
                                    {
                                        <tr>
                                            <td>@item.ChanellFormat</td>
                                            <td>@item.Status</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                        <td>
                            <form method="post" asp-action="Delete" asp-controller="Chanell">
                                <input type="hidden" name="Name" value="@frequency.Name" />
                                <input type="hidden" name="Sources" value="@frequency.Sources" />
                                <button type="submit" class="btn btn-danger">წაშლა</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>