GlobalManagment/Controllers/SatteliteChanellsController.cs
using Jandag.BLL.Interface;
using Jandag.BLL.Models;
using Jandag.BLL.Models.ViewModels;
using Jandag.Persistance.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace GlobalManagment.Controllers
{
    public class SatteliteChanellsController : Controller
    {
        private readonly ISatteliteFrequencyService ser;
        private readonly IService chanells;
        public SatteliteChanellsController(ISatteliteFrequencyService se, IService chanells)
        {
            this.ser = se;
            this.chanells = chanells;
        }

        public async Task<IActionResult> Index()
        {
            var res = await ser.GetMonitoringFrequencies();
            var ports = await chanells.GetPortsWhereAlarmsIsOn();
            foreach (var item in res)
            {
                foreach (var it in item.details)
                {
                    if (ports.Contains(it.PortIn250))
                    {
                        it.HaveError = true;
                    }
                    else
                    {
                        it.HaveError = false;
                    }

                }
            }
            return View(res);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Post(SatteliteFrequencyModel mod)
        {
            try
            {
                var res = await ser.AddAsync(mod);
                if (res)
                {
                    return RedirectToAction("Details");
                }

                throw new ArgumentException("Gaxaria");

            }
            catch (Exception)
            {

                throw;
            }
        }

        public async Task<IActionResult> Details()
        {
            List<FrequencyDeleteModel> mod = new List<FrequencyDeleteModel>();
            var res = await ser.GetAllAsync();
            foreach (var item in res)
            {
                mod.Add(new FrequencyDeleteModel()
                {
                    Degree = item.Degree,
                    Frequency = item.Frequency,
                    Polarization = item.Polarisation,
                    SymbolRate = item.SymbolRate,
                    PortIn250 = item.PortIn250,
                });
            }
            return View(mod);
        }

        [HttpPost]
        public IActionResult Edit(FrequencyDeleteModel mod)
        {
            throw new ArgumentException("varedaqtireb");

        }

        [HttpPost]
        public async Task<IActionResult> Delete(FrequencyDeleteModel mod)
        {
            await ser.Delete(mod.PortIn250);
            return RedirectToAction("Details");
        }

        [HttpGet]
        public async Task<IActionResult> ViewAdditionalDetails(int frequency)
        {
            var mod = await ser.GetDetailsByEmrport(frequency);
            return View(mod);
        }
    }
}

GlobalManagment/Controllers/TranscoderController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Jandag.BLL.Interface;
using Jandag.BLL.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GlobalManagment.Controllers
{
    public class TranscoderController : Controller
    {
        private readonly ITranscoderService ser;

        public TranscoderController(ITranscoderService se)
        {
            this.ser = se; 
        }
        public async Task< IActionResult> Index()
        {
            var mod = await ser.GetAllAsync();
            return View(mod);
        }

        [HttpPut]
        public IActionResult Update(TranscoderViewModel mod)
        {
            throw new ArgumentException("Go away  from me");
        }

        public async Task<IActionResult> Add()
        {
            var res = await ser.GetDropDownList();
            return View(res);
        }

        [HttpPost]
        public async Task<IActionResult>Insert(TranscoderViewModel mod)
        {

            try
            {
                var res = await ser.AddAsync(mod);
                if (res)
                {
                    return RedirectToAction("Index");
                }
                TempData["Error"] = "modeltate kia validuri";
                return RedirectToAction("Add");
            }
            catch (Exception exp)
            {
                TempData["Error"] = exp.Message;
                return RedirectToAction("Add");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                await ser.Delete(id);
            }
            return RedirectToAction("Index");
        }
    }
}

GlobalManagment/Views/Transcoder/Add.cshtml
@using Jandag.BLL.Models.ViewModels
@model TranscoderViewModel
<!DOCTYPE html>
<html>
<head>
   
    <title>თანამგზავრი</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #B2B377;
            font-family: Arial, sans-serif;
        }

        .container {
            margin-top: 5px;
            border-radius: 30px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 30px;
            background-color: #FFF8DC;
        }

        h2 {
            color: black;
            margin-bottom: 20px;
            margin-left: 210px;
            font-weight: 600;
        }

        .form-group {
            margin-bottom: 30px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        input[type="number"] {
            border: 1px solid #ced4da;
            border-radius: 20px;
            padding: 10px;
            width: 100%;
            font-size: 20px;
            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif,'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            background-color: #FFF8DC;
            font-weight: 400;
        }

            input[type="text"]:focus,
            input[type="number"]:focus {
                border-color: #007bff;
                outline: none;
            }

        .btn-primary {
            background-color: #007bff;
            border: none;
            border-radius: 120px;
            padding: 10px 20px;
            margin-left: 450px;
        }

            .btn-primary:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <div class="message-box">
        @if (TempData["Error"] != null)
        {
            <div class="error-message">
                <script>
                    alert('@TempData["Error"]');
                </script>
            </div>
        }
        @if (TempData["success"] != null)
        {
            <div class="success-message">
                <script>
                    alert('@TempData["success"]');
                </script>
            </div>
        }
    </div>
    <div class="container">
        <h2>არხის დამატება ტრანსკოდერში</h2>
        <form asp-action="Insert" asp-controller="Transcoder">
            <div class="form-group">
                <label asp-for="Id">წყარო</label>
                <select asp-for="Id" asp-items="Model.CHanellNameList" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="TranscodingFormat">ტრანსკოდირების ფორმატი</label>
                <select asp-for="TranscodingFormat" asp-items="Model.TranscodingFormatList" class="form-control"></select>

                <label asp-for="EmrNumber">EMR</label>
                <select asp-for="EmrNumber" asp-items="Model.EmrNumberList" class="form-control"></select>

                <label for="Card">ქარდი</label>
                <input required type="number" class="form-control" asp-for="Card" id="Card" placeholder="მაგ: 4" />

                <label for="Port">პორტი</label>
                <input type="number" required class="form-control" asp-for="Port" id="Port" placeholder="მაგ:5" />
            </div>
            <button type="submit" class="btn btn-primary">დამატება</button>
        </form>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

GlobalManagment/Views/Transcoder/Index.cshtml
@using Jandag.BLL.Models.ViewModels
@model IEnumerable<TranscoderViewModel>
@{
    ViewData["Title"] = "Index";
}
<div class="message-box">
    @if (TempData["Error"] != null)
    {
        <div class="error-message">
            <script>
                alert('@TempData["Error"]');
            </script>
        </div>
    }
    @if (TempData["success"] != null)
    {
        <div class="success-message">
            <script>
                alert('@TempData["success"]');
            </script>
        </div>
    }
</div>
<h2 class="text-center">ტრანსკოდერის ინფორმაცია</h2>
<title>ტრანსკოდერი</title>
<head>
    <style>
        body {
            background-color: #B2B377;
            color: #8B4513; 
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }

        h1, h2, h3 {
            color: #8B4513;
        }

        a {
            color: #FF4500;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }

        .container {
            max-width: 1500px;
            margin: 0 auto;
            background-color: #FFF8DC;
            padding: 20px;
            border-radius: 50px;
        }

        .button {
            background-color: #FF6347;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 10px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

            .button:hover {
                background-color: #CD5C5C;
            }

        .footer {
            text-align: center;
            margin-top: 20px;
            padding: 10px 0;
            background-color: #FFE4E1;
        }

    </style>
</head>
<body>
    <form asp-action="Add" asp-controller="Transcoder" method="get">
        <button type="submit" class="btn btn-primary">დამატება</button>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>არხის სახელი</th>
                <th>ფორმატი</th>
                <th>EMR</th>
                <th>სიჩქარე</th>
                <th>ქარდი</th>
                <th>პორტი</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var frequency in Model)
            {
                <tr>
                    <td>@frequency.Id</td>
                    <td>@frequency.TranscodingFormat</td>
                    <td>@frequency.EmrNumber</td>
                    <td>@frequency.Card</td>
                    <td>@frequency.Port</td>
                    <td class="containera">
                        <form method="get" asp-action="Delete" asp-asp-controller="Transcoder">
                            <input type="hidden" name="id" value=@frequency.Id>
                            <button type="submit" class="btn btn-danger">წაშლა</button>
                        </form>
                        @*  <form method="post" asp-action="Edit" asp-asp-controller="SatteliteChanells">
                    <input type="hidden" name="Degree" value="@frequency.Degree" />
                    <input type="hidden" name="PortIn250" value="@frequency.PortIn250" />
                    <input type="hidden" name="SymbolRate" value="@frequency.SymbolRate" />
                    <input type="hidden" name="Frequency" value="@frequency.Frequency" />
                    <input type="hidden" name="Polarization" value="@frequency.Polarization" />
                    <button type="submit" class="btn btn-primary">რედაქტირება</button>
                    </form> *@
                    </td>
                </tr>
            }
        </tbody>
    </table>
  
</body>